auth:
  rabbit_user: admin
  rabbit_pass: testpass

rabbit_hosts:
  host: a.b.c.d

## If the interfaces are bonded together, define each one separately here.
## On CDN nodes find it out this way: sudo cat /proc/net/bonding/bond0 | grep "Slave Interface"
devices:
  - ens1f1
  - ens1f0
